### ISSUE TITLE
tinker python packaging

### ISSUE THREAD

**Issue by TomasTomecek** [TomasTomecek/ansible-bender#22]
and make @webknjaz happy :sun_with_face: 

https://github.com/TomasTomecek/ansible-bender/commit/c27b956046212ac9fd83a62729a9e8415c2536cd#r31244032
console scripts as dict: https://github.com/cherrypy/cherrypy/blob/master/setup.py#L58
https://github.com/TomasTomecek/ansible-bender/commit/a1c36aa593dbf375e2769c6d3fb97c4d1a4fea09#r31243907
https://github.com/TomasTomecek/ansible-bender/commit/c27b956046212ac9fd83a62729a9e8415c2536cd#r31243932

**Comment by webknjaz** [comment]
😂

@webknjaz was a mentor @ PyPI packaging sprint two weeks ago 8n London and still is under impression :)

Also, I know a lot about how deeply packaging is broken in Python and want to fix this..
You can read some details at packaging.python.org
