### ISSUE TITLE
Do not pull image

### ISSUE THREAD

**Issue by ladisone** [TomasTomecek/ansible-bender#36]
Hello, i run this example command as non root user

`ansible-bender build -e SOME=VALUE -l some=other-value -- ./tests/data/basic_playbook.yaml docker.io/library/python:3-alpine this-is-my-image`

Return:

```
22:35:52.255 utils.py          INFO   running command: "['buildah', 'inspect', '-t', 'image', 'docker.io/library/python:3-alpine']"
22:35:52.255 utils.py          DEBUG  buildah inspect -t image docker.io/library/python:3-alpine
22:35:52.315 utils.py          ERROR  error reading image "docker.io/library/python:3-alpine": error reading image: error locating image "docker.io/library/python:3-alpine" for importing settings: error locating image with name "docker.io/library/python:3-alpine": image not known
```

Edit: @TomasTomecek fixed the formatting

**Comment by TomasTomecek** [comment]
Hi, thanks for reporting. I did not understand the issue at first, because I knew that ab is able to pull the base image if it's not present locally. But looking at the code right now, I can clearly see it just can't work.

I'm gonna fix this and write a test for it so it won't happen in future.

**Comment by ladisone** [comment]
Hi Tom, I have other mistakes.  Can I report you Czech?

**Comment by TomasTomecek** [comment]
Yes, feel free to send me an e-mail: tomas@tomecek.net, but don't expect much of me since it's almost christmas time.
