### ISSUE TITLE
Support annotation option

### ISSUE THREAD

**Issue by garyedwards** [TomasTomecek/ansible-bender#62]
Hi thanks for a great project.  It would be good if `ansible-bender build` supported the --annotation option present in both buildah and podman.

This is commonly used for triggering oci hooks.

**Comment by TomasTomecek** [comment]
Hi! Thanks for your feedback.

I can see the option:
```
$ podman build -h | grep anno
   --annotation value              Set metadata for an image (default [])

$ buildah config --help | grep anno
  -a, --annotation annotation      add annotation e.g. annotation=value, for the target image (default [])
```

Actually, I've never used it. Would the expectation be just to add a new CLI option to the build command, i.e. `--annotation key=value` and "forward" those annotations when doing `buildah config`?

**Comment by garyedwards** [comment]
Hi Tomas, the expectation would be exactly as you describe, similar to how you currently deal with labels and ENV options.

**Comment by TomasTomecek** [comment]
Cool! I'll try to land this into next release.
