### ISSUE TITLE
Install for people new to podman & builder

### ISSUE THREAD

**Issue by bryfry** [TomasTomecek/ansible-bender#87]
There were lots of configurations that needed to be setup and a few dependencies that needed installed in addition to just, in my case, apt installing buildah and podman.  

It might be useful to give and example of at least one distro full install from scratch.

I eventually ran into this error which may have to do with my buildah setup.

```
TASK [Gathering Facts] ************************************************************************************************************************************************************************************************************
fatal: [a-very-nice-image-20190304-233906036203-cont]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /tmp/ansible-tmp-1551760750.1174574-100238936710490 `\" && echo ansible-tmp-1551760750.1174574-100238936710490=\"` echo /tmp/ansible-tmp-1551760750.1174574-100238936710490 `\" ), exited with result 1", "unreachable": true}
```

**Comment by TomasTomecek** [comment]
Yes, it's very likely that buildah is spitting errors and that confuses ansible badly. If you rerun the command like this, it should give you a clear answer what the errors is:
```
$ ansible-bender --debug build --extra-ansible-args='-vvvvvv'
```

Let me do a brief PR - I agree that setting up rootless podman/buildah is not trivial.

**Comment by TomasTomecek** [comment]
please check out the linked PR whether it addresses your issue

**Comment by bryfry** [comment]
I will use both the verbose output and your additional inductions and
report on my results.

Thank you!

**Comment by TomasTomecek** [comment]
Oki, I'm going to merge my docs PR and close this issue. Please open a new one with your findings so that we can address the underlying issue.
